### ISSUE TITLE
Double "back" before exit

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#33]
**Is your feature request related to a problem? Please describe.**
The app should double check before exiting, After the first close request, it should give a toast saying "Press back again to exit"

**Additional context**
If and only in you're on the main page or the login page, this should happen

**Comment by YuvrajSingh3110** [comment]
Assign this issue to me

**Comment by YuvrajSingh3110** [comment]
The double back feature does not seem to be implemented correctly as the WillPopScope widget is deprecated now and the logic of this feature is not working everytime in PopScope widget. It works only when the screen is launched first time when the app is created. I think we can make a pop up asking to exit instead of double back.

**Comment by Abhigyan103** [comment]
Any update ?

**Comment by YuvrajSingh3110** [comment]
Actually i looked up for why my logic wasn't working properly with gorouter and I found there is a issue for the same in flutter sdk for gorouter and willpopscope which hasn't been solved yet. If you know of a soution for this please tell me
https://github.com/flutter/flutter/issues/102408

**Comment by AnanyaSinghal23** [comment]
@Abhigyan103 I would like to work on the issue under JWOC

**Comment by SharmaDhruv2511** [comment]
@Abhigyan103 /attempt

**Comment by Abhigyan103** [comment]
Any update ?

**Comment by AnanyaSinghal23** [comment]
Will be making the update by tonight. Need to test it.
